name: msds-686
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.22.0
  - keras=2.11.0
  - matplotlib=3.7.1
  - numpy=1.24.2
  - pandas=1.5.3
  - pip=22.3.1
  - python=3.10.8
  - scikit-learn=1.2.2
  - tensorflow=2.11.0
